### PR TITLE
Get max extent CRS from QGIS API.

### LINKED ISSUE #429: Add `extent` parameter to  initConfig API `crs` section.
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

For third part maps like 'Gmap', 'Bing', 'OSM' for some CRS is necessary declare max extention in current epsg map units.

### Suggested solution

Add `extent` parameter to initConfig API , i.e.:

```python
...
"crs": {
            "epsg": 32632,
            "proj4": "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs",
            "geographic": false,
            "axisinverted": false,
            "extent": [
                166021.44308053964,
                0.0,
                534994.6550611362,
                9329005.182447437
            ]
        },
...
```

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by wlorenzetti**
Closes: #429

### CODE REVIEW

**Comment by wlorenzetti** [comment]
@volterra79 I just add a new api to get information about CRS, i.e.:
```
/crs/3003
```
return
```
{
    "result": true,
    "data": {
        "epsg": 3003,
        "proj4": "+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs",
        "geographic": false,
        "axisinverted": false,
        "extent": [
            1226046.6820902952,
            4047095.260762165,
            1727931.8998958569,
            5214000.012210975
        ]
    }
}
```

**Comment by volterra79** [comment]
@wlorenzetti thanks

**Comment by wlorenzetti** [comment]
@volterra79 tell me when you want I merge it on dev.

**Comment by volterra79** [comment]
@wlorenzetti you can merge it. Thanks

**Pull request merged**
