### PR TITLE
:sparkles: Add new project option: `WMS GetMap image format`

### LINKED ISSUE #626: :sparkles: Add possibility to choose for every project image format of WMS GetMap response
### Checklist

- [X] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

At now G3W-SUITE use only the image format `image/png` for WMS _GetMap_ request. It could be useful to give to the G3W-SUITE administration projects the capability to choose the image format of WMS _GetMap_ request.

The value available will be the standard formats that QGIS server can manage:

- jpg
- jpeg
- image/jpeg
- image/png
- image/png; mode=1bit
- image/png; mode=8bit
- image/png; mode=16bit

https://docs.qgis.org/3.28/it/docs/server_manual/services/wms.html#wms-getmap-format

### Suggested solution

Create e new select-box input inside the project form for choose the _GetMap_ image format of the webgis service:

Screenshot_20231016_091030

Suggest to set PNG mode=8bit as default format.

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by wlorenzetti**
Closes: #626 
Related to: #314

### CODE REVIEW

**Comment by wlorenzetti** [comment]
@volterra79 there is a conflict, what version I have to accept?

**Comment by volterra79** [comment]
> @volterra79 there is a conflict, what version I have to accept?

@wlorenzetti you have to accept the last one app.min.js base on https://github.com/g3w-suite/g3w-admin/pull/627/commits/cd78cedc14f6091038f53edafcada8d82de72691

**Comment by Raruto** [comment]
@wlorenzetti this option name is a bit ambiguous, perhaps you meant something like `"auto"` (ie. use server default value)?

image

**Comment by wlorenzetti** [comment]
> @wlorenzetti this option name is a bit ambiguous, perhaps you meant something like `"auto"` (ie. use server default value)?
> 
> image

Thanks @Raruto I'll fix it.

**Comment by Raruto** [comment]
@wlorenzetti please double check too, maybe you missed the [`image/png; mode=1bit`](https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#format) option

**Comment by Raruto** [comment]
@wlorenzetti I would recommend starting include some links to documentation next to various options:

Something like the following:

```html
<a title="QGIS Docs" target="_blank" href="https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#wms-getmap-format">
  <span class="glyphicon glyphicon-question-sign"></span>
</a>
```

image

**PS** If you open an existing project do you see PNG 1bit as default?
Creating a new project instead I get PNG 8bit (which I guess is the default).

**Comment by Raruto** [comment]
> If you open an existing project do you see PNG 1bit as default?

I guess it's related to migrations not applied (is really there no way to re-apply them?).

image

re-saving that project instead I get the 1-bit configuration shown by default:

image

**Comment by wlorenzetti** [comment]
> I guess it's related to migrations not applied (is really there no way to re-apply them?).

Did you try running `manage.py migrate qjdango <migration_name>` https://docs.djangoproject.com/en/4.2/topics/migrations/#reversing-migrations

I think that is very old PR and migration is not see by Django

**Comment by Raruto** [comment]
Nope..

```
manage.py migrate qdjango 0109_project_wms_getmap_format
```

image

Anyway, to replicate it I did as follows:

1. shut down docker
2. move to [dev](https://github.com/g3w-suite/g3w-admin/tree/dev) branch
3. turn on down docker
4. create a new project
5. shut down docker
6. move to [wms_getmap_format](https://github.com/g3w-suite/g3w-admin/tree/wms_getmap_format) branch
7. turn on down docker
8. open project settings
9. the default setting is PNG 1bit

**Comment by wlorenzetti** [comment]
@Raruto https://github.com/g3w-suite/g3w-admin/blob/wms_getmap_format/g3w-admin/qdjango/models/projects.py and https://github.com/g3w-suite/g3w-admin/blob/wms_getmap_format/g3w-admin/qdjango/forms/projects.py they have non-pythonic formatting, please restore it, thanks.

**Comment by wlorenzetti** [comment]
@Raruto I fixed migrations and others, the default value fo select id PNG8. Can I merge it?

**Comment by Raruto** [comment]
> the default select value is PNG8

@wlorenzetti that's the correct behavior when creating a new project directly from [`wms_getmap_format`](https://github.com/g3w-suite/g3w-admin/tree/wms_getmap_format) branch.

> ref: https://github.com/g3w-suite/g3w-admin/pull/627#issuecomment-1824066071

I always get PNG 1bit when trying to migrate a project precendetly created from [`dev`](https://github.com/g3w-suite/g3w-admin/tree/dev) to [`wms_getmap_format`](https://github.com/g3w-suite/g3w-admin/tree/wms_getmap_format).

It doesn't seem to change much after trying to force reapplying the migration:

```sh
manage.py migrate --fake qdjango 0109_project_wms_getmap_format
manage.py migrate qdjango 0109_project_wms_getmap_format
```

ref: https://stackoverflow.com/questions/31953587/rerun-a-django-data-migration

**Comment by wlorenzetti** [comment]
> > the default select value is PNG8
> 
> @wlorenzetti that's the correct behavior when creating a new project directly from [`wms_getmap_format`](https://github.com/g3w-suite/g3w-admin/tree/wms_getmap_format) branch.
> 
> > ref: [#627 (comment)](https://github.com/g3w-suite/g3w-admin/pull/627#issuecomment-1824066071)
> 
> I always get PNG 1bit when trying to migrate a project precendetly created from [`dev`](https://github.com/g3w-suite/g3w-admin/tree/dev) to [`wms_getmap_format`](https://github.com/g3w-suite/g3w-admin/tree/wms_getmap_format).
> 
> It doesn't seem to change much after trying to force reapplying the migration:
> 
> ```shell
> manage.py migrate --fake qdjango 0109_project_wms_getmap_format
> manage.py migrate qdjango 0109_project_wms_getmap_format
> ```
> 
> ref: https://stackoverflow.com/questions/31953587/rerun-a-django-data-migration

Ok I think you have a broken migrations db structure, I just merge it and after if necessary I'll make a fix on migrations.

**Pull request merged**
