### PR TITLE
✨ Filter group bar

### LINKED ISSUE #808: Filter displayed groups
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

In the list of Cartographic Groups it is necessary to be able to filter the Groups based on the MacroGroup they belong to.

### Suggested solution

Once the MacroGroup has been chosen (for example from a drop-down menu), the name of the chosen Macrogroup and only the associated Groups must be reported

Remember that there may be Groups not associated with any MacroGroup

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by wlorenzetti**
Closes: #808

Added a filter box for filtering _cartographic groups_ by _macrogroup_

Screenshot_20240410_153427

Screenshot_20240410_153456

### CODE REVIEW

**Comment by wlorenzetti** [comment]
@leolami does it make sense that the _Editor Level 2_ user can filter by macrogroups?

**Comment by leolami** [comment]
yes, if Editor2 is the administrator of Groups belonging to multiple MacroGroups

And this can happen especially in the case in which the MacroGroups are created solely for the organizational purposes of the Groups

**Comment by wlorenzetti** [comment]
> yes, if Editor2 is the administrator of Groups belonging to multiple MacroGroups
> 
> And this can happen especially in the case in which the MacroGroups are created solely for the organizational purposes of the Groups

Only Editor1 can be the administration of Groups, Editor2 can just only create single project

**Comment by leolami** [comment]
Yes true.
However, if an Editor2 manages multiple Groups placed in different MacroGroups, he may need to filter them and then go to the right Group and load his projects

**Pull request merged**
