### PR TITLE
Fix `usecompleter` value in /vector/api/confgi

### LINKED ISSUE #785: ValueRelation editing widget option `UseCompleter` fail.
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

If a field of a layer has a `ValueRelation` widget active, is it possible set for it the `User completer` on QGIS desktop interface:

Screenshot_20240321_164734

the relative /vector/api/config repsonse for the layer  return the `usecompleter` property:

```json
 "input": {
       "type": "select_autocomplete",
        "options": {
          "values": [],
           "default": null,
            "key": "name",
            "value": "code",
            "usecompleter": false,
            "layer_id": "roads_ea006d6f_bd87_4635_aae0_4e9e7842b3f4",
            "loading": {
              "state": null
            },
            "filter_expression": null
 }
```

checking the `UseCompleter` :

Screenshot_20240321_165517

the API response contain again `usecompleter` set to true

```json
 "input": {
       "type": "select_autocomplete",
        "options": {
          "values": [],
           "default": null,
            "key": "name",
            "value": "code",
            "usecompleter": false,
            "layer_id": "roads_ea006d6f_bd87_4635_aae0_4e9e7842b3f4",
            "loading": {
              "state": null
            },
            "filter_expression": null
 }
```

### Steps to reproduce

1. go to [public-building-management-demo/layers](https://dev.g3wsuite.it/en/qdjango/g3w-suite-demo/projects/public-building-management-demo/layers/#)
2. download the project
3. modify the ValueRelation UserCompleter parameter
4. save again the project in G3W-SUITE  
5. check /vector/api/config/qdjango/336/buildings_2f43dc1d_6725_42d2_a09b_dd446220104a/

### Environment

- g3w-admin: __3.7.dev-20240319064048__
- g3w-client: __3.10.0-alpha.1__
- editing: __3.8.0-alpha.1__
- qtimeseries: __undefined__
- browser: __Firefox 125.0__
- operating system: __Linux 64-bit__

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by wlorenzetti**
Closes: #785

### CODE REVIEW

**Comment by wlorenzetti** [comment]
@volterra79 this fix the `usecompleter` value.

**Comment by wlorenzetti** [comment]
@volterra79 I just make a test, the auto completation is active and works fine, but the pick from layer feature not working, if `usercompleter` is true

pick

**Comment by volterra79** [comment]
> @volterra79 I just make a test, the auto completation is active and works fine, but the pick from layer feature not working, if `usercompleter` is true
> 
> pick

@wlorenzetti i'll check

**Comment by volterra79** [comment]
> > @volterra79 I just make a test, the auto completation is active and works fine, but the pick from layer feature not working, if `usercompleter` is true
> > pick
> 
> @wlorenzetti i'll check

@wlorenzetti fixed with https://github.com/g3w-suite/g3w-client/pull/600/commits/1078ff7b293e0a540110da4bfc79ddc95eaa938f

**Pull request merged**
