### PR TITLE
Delete docs folder and move documentation to new repository.

### LINKED ISSUE #375: Move `docs` folder into `g3w-suite-documentation` repository
~~Nowdays many installations take advantage of docker, so it may be advisable to keep the documentation in the same place as the code used by the end users:~~

~~[`g3w-admin/docs`](https://github.com/g3w-suite/g3w-admin/blob/12024ef814cfe1c2bd56f097936521d6988e6c67/docs) --> [`g3w-suite-docker/docs`](https://github.com/g3w-suite/g3w-suite-docker)~~

To keep track of any new needed changes (aka. issues and pull requests) and possibly simplify the process of new edits by other users it's best to keep your user documentation in one dedicated place.

Ref: https://g3w-suite.readthedocs.io/

### PR DESCRIPTION
**Pull request by wlorenzetti**
Closes: #375

### CODE REVIEW

**Comment by Raruto** [comment]
@wlorenzetti I haven't forgotten about this, but I'm also trying to review the pull locally to make the README lighter and more consistent with the client.

**Comment by wlorenzetti** [comment]
> @wlorenzetti I haven't forgotten about this, but I'm also trying to review the pull locally to make the README lighter and more consistent with the client.

@Raruto did you do it?

**Comment by Raruto** [comment]
> @Raruto did you do it?

@wlorenzetti Yes, I think it might be pretty good for now (I haven't checked all the installation steps in detail, but at least I hope they are now listed in a sequential order).

---

If possible, could you also add the following URL in the **About** section of this repository? 

```
Server module for G3W-SUITE 

https://g3w-suite.readthedocs.io/en/latest/g3wsuite_administration.html
```

**Comment by wlorenzetti** [comment]
> If possible, could you also add the following URL in the **About** section of this repository?
> 
> ```
> Server module for G3W-SUITE 
> 
> https://g3w-suite.readthedocs.io/en/latest/g3wsuite_administration.html
> ```

Done!

**Pull request merged**
