### PR TITLE
Fix upload `.qgz` project file

### LINKED ISSUE #543: Error on upload `.qgz` QGIS project file
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

On uploading of QGIS project `.qgz` file you get the following error:

Screenshot_20230504_094634

### Steps to reproduce

1. Make a QGIS project with .qgz extention
2. Create e new qdjango project by `/qdjango/<group_slug>/project/add/`.
3. Try to save.

### Environment

- g3w-admin: 3.6.dev-20230503103435
- browser: Firefox Developer Edition 113.0b9 (64 bit)
- operating system: Ubuntu 22.04

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by wlorenzetti**
Fix reading `.qgz` QGIS project file on create new one or update.

Closes: #543

### CODE REVIEW

**Comment by wlorenzetti** [comment]
This PR fix also this: https://github.com/g3w-suite/g3w-admin/issues/542#issuecomment-1532996014

**Comment by wlorenzetti** [comment]
@volterra79 can you check it ASAP? Thanks.

**Comment by Raruto** [comment]
I tried to test this pull following the steps of https://github.com/g3w-suite/g3w-admin/issues/480, but i get the following:

image

## Request Headers

```
PATCH /en/dff/upload/4045ccf2-04b9-454d-b1f6-5b19d6ffc58a HTTP/1.1
Host: localhost:8000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: */*
Accept-Language: en-US,it-IT;q=0.7,it;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:8000/en/admin/qdjango/buildings/projects/update/public-building-management-demo/
Tus-Resumable: 1.0.0
Upload-Offset: 0
Content-Type: application/offset+octet-stream
X-CSRFToken: FIbazIZUXaosGaDovA49kXdvWuZm7rv18ImeLM6IhKkkHrNkO1QBcxbZ02MNjCV2
Content-Length: 1226140
Origin: http://localhost:8000
DNT: 1
Connection: keep-alive
Cookie: csrftoken=RnBK4NIE797RHumldI07n3Uwzg6NJRLmknMOgRPsrJ3JILwhw9MzfDS0DOTeV2bn; gi3w-suite-dev-iehtgdb264t5gr=n93mb99nsu1zayg5t34pzf1mw0w8fnyg; cookieconsent_status=dismiss; g3wclientsessiontoken=427fcd13031448ba9b07f12e87bc135a
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
```


## Response Headers
```
HTTP/1.1 410 Gone
Server: gunicorn
Date: Thu, 04 May 2023 14:12:25 GMT
Connection: close
Content-Type: text/html; charset=utf-8
Tus-Resumable: 1.0.0
Tus-Version: 1.0.0
Tus-Extension: creation,termination,file-check
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: PATCH,HEAD,GET,POST,OPTIONS
Access-Control-Expose-Headers: Tus-Resumable,upload-length,upload-metadata,Location,Upload-Offset
Access-Control-Allow-Headers: Tus-Resumable,upload-length,upload-metadata,Location,Upload-Offset,content-type
Cache-Control: no-store
X-Frame-Options: DENY
Content-Length: 0
Content-Language: en
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Vary: Origin
Access-Control-Allow-Credentials: true
```

**Comment by wlorenzetti** [comment]
This issue is related to django-file-form and caching problem (http://mbraak.github.io/django-file-form/details/) 

> Local-memory caching

> Don't use local-memory caching in your Django configuration if you use a multi process WSGI server. It will break file uploads, because file uploads use the Django cache and might hit different WSGI processes.

    

> The default cache option in Django is local-memory caching.

> Most WSGI servers are multi process.

Infact for production deploy I add django-redis module and move caching backend on redis https://github.com/g3w-suite/g3w-suite-docker/pull/96.

So because you use docker for delveloping I suggest to use redis as caching system or to pull down the gunicorn workers to 1.

**Review by volterra79 — APPROVED** [review]

**Pull request merged**
