### PR TITLE
Set a default fallback image as Group header logo image on save (ref: `CLIENT_G3WSUITE_LOGO`)

### LINKED ISSUE #498: Optional project logo/picture
### Checklist

- [x] I've searched through the [current issues](https://github.com/g3w-suite/g3w-admin/issues) to make sure this feature hasn't been requested already.

### Motivation

In ored to speed up the creation / testing of new projects it would be better to make this value optional (i.e. prefilled with a placeholder image).

### Suggested solution

1. always show a fallback image in the upload field

image

2. or, always return the suite logo (eg. `G3WSUITE_MAIN_LOGO = 'img/g3wsuite_logo.png'`) if that value is not already setted within the administrative interface:

image

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by wlorenzetti**
Closes: #498

### CODE REVIEW

**Comment by Raruto** [comment]
@volterra79 by chance, do you encounter any particular issues with this edit?

I'm not really sure if it's related, but after I switched to this branch I got all the admin CSS and JS files messed up (ie. 4xx error)

**Comment by volterra79** [comment]
> @volterra79 by chance, do you encounter any particular issues with this edit?
> 
> I'm not really sure if it's related, but after I switched to this branch I got all the admin CSS and JS files messed up (ie. 4xx error)

@Raruto i need to try. I let you know

**Review by Raruto — CHANGES_REQUESTED** [review]
## Test perfomed: "deleting a previously uploaded image"

The image field is still mandatory if you try to delete a previously uploaded image. The problem here lies in the fact that the form interface does not show the field as mandatory (e.g. with an asterisk) before saving (or it's just an oversight and the field must always be optional).

image


image

**Comment by wlorenzetti** [comment]
@Raruto ok we left field mandatory, but we set by default a logo image.

**Comment by Raruto** [comment]
@wlorenzetti Good enough, I would also consider this other change:

## BEFORE: `background-repeat: repeat;`

image

## AFTER: `background-repeat: no-repeat;`

image

**Review by Raruto — APPROVED** [review]

**Pull request merged**
